### PR TITLE
Live area coords

### PR DESCRIPTION
**Pull request by mdgardiner**

### CODE REVIEW

**Comment by mike-suggitt** [comment]
Area coords should already be realtime reflection of the cropping??

**Comment by tayloc01** [comment]
Yes Mike, it is. But we need it to be exposed via events even when doing a manual crop. So we can display it in the crop preview.

PS. don't you have more important UI Consultant work to do than pestering us on here?

**Comment by mike-suggitt** [comment]
Fair enough. Haha yea I do but can't pass an opportunity to throw out some
passive-aggressive comments :D

**Comment by steven2y** [comment]
+1

**Comment by jmaciasluque** [comment]
:laughing: :laughing: :laughing: :laughing: :laughing:

**Pull request merged**
